<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\MRPrintHub.Core\MRPrintHub.Core.csproj" />
    <ProjectReference Include="..\MRPrintHub.QR\MRPrintHub.QR.csproj" />
    <ProjectReference Include="..\MRPrintHub.Storage\MRPrintHub.Storage.csproj" />
  </ItemGroup>
</Project>
