<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>MRPrintHub.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="MRPrintHub.ico" />
    <Resource Include="MRPrintHub.png" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MRPrintHub.Core\MRPrintHub.Core.csproj" />
    <ProjectReference Include="..\MRPrintHub.QR\MRPrintHub.QR.csproj" />
    <ProjectReference Include="..\MRPrintHub.Network\MRPrintHub.Network.csproj" />
    <ProjectReference Include="..\MRPrintHub.Storage\MRPrintHub.Storage.csproj" />
  </ItemGroup>
</Project>
